puts "The student of Villains Academy"
puts "------------"
puts "Dr, Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "michael Corleone"
puts "Aslec DeLarge"
puts "The Wicked Witch of the West"
puts "Terminator"
puts "Freddy Krueger"
puts "The Joker"
puts "Joffrey Baratheon"
puts "Norman Bates"